POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJyaWFuMTIzIiwiaWQiOiI2MzYxNWE4NDUyMzZiMmQzMDk2MTQwNjciLCJpYXQiOjE2NjczMjc0NDZ9.XtWRxe0v6Ae3RfwRM-HnCERHc0iuabFWsff04DQmR_k

{
    "content":"dsadsdsadsa",
    "important":true,
    "userId": "63615a845236b2d309614067"
}