PUT http://localhost:3001/api/notes/636170d3c64377a84d8d6d1b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJyaWFuMTIzIiwiaWQiOiI2MzYxNWE4NDUyMzZiMmQzMDk2MTQwNjciLCJpYXQiOjE2Njc0MTUxMTZ9.IiMZ4os960uV5EB8Ke74h2TQD3U4eh-QkvI3d0KUakI

{
    "content": "cdsadggfgfsfdsfsdfsdadas",
    "important" :false
}